### ISSUE TITLE
Configuration loading error

### ISSUE THREAD

**Issue by realSimon157** [GRX005/PlaytimeLink#2]
Server log (pufferfish 1.20.4):
```
[Server thread/ERROR]: Error occurred while enabling PlaytimeLink v1.4 (Is it up to date?)
java.lang.RuntimeException: java.nio.file.NoSuchFileException: plugins/PlaytimeLink\config.yml
	at _1ms.playtimelink.Main.checkAndUpdateConfig(Main.java:88) ~[PlaytimeLink.jar:?]
	at _1ms.playtimelink.Main.onEnable(Main.java:29) ~[PlaytimeLink.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:672) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:311) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.nio.file.NoSuchFileException: plugins/PlaytimeLink\config.yml
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:261) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:379) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:431) ~[?:?]
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420) ~[?:?]
	at java.nio.file.Files.newInputStream(Files.java:159) ~[?:?]
	at java.nio.file.Files.newBufferedReader(Files.java:2897) ~[?:?]
	at java.nio.file.Files.readAllLines(Files.java:3392) ~[?:?]
	at java.nio.file.Files.readAllLines(Files.java:3433) ~[?:?]
	at _1ms.playtimelink.Main.checkAndUpdateConfig(Main.java:78) ~[PlaytimeLink.jar:?]
	... 13 more
[Server thread/INFO]: [PlaytimeLink] Disabling PlaytimeLink v1.4
```

**Comment by GRX005** [comment]
Thanks for reporting, fixed.
